version: "3.8"

networks:
  shared-network:
    name: shared-network
    driver: bridge

services:
  app:
    image: saymkarjat/weather-spring:latest
    container_name: weatherspring
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/pogoda
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      OPENWEATHER_API_KEY: ${OPENWEATHER_API_KEY}
    networks:
      - shared-network
    depends_on:
      - db

  db:
    image: postgres:15.3
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pogoda
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - shared-network

volumes:
  postgres-data:
